
<?php

 $apiKey = "rzp_test_Wi972bG7df7ltY";

?>


<?php
session_start();
error_reporting(0);

 
$conn= new mysqli('localhost','root','','shopping')
or die("Could not connect to mysql".mysqli_error($conn));

  

$name=$_POST['first_name'];
$address = $_POST['address'];
$email=$_POST['email'];
$contactno=$_POST['contact'];
//$city=$_P['ct'];



 $query1=mysqli_query($conn,"insert into  payment value('$name','$address','$email','$contactno','bhvn')");
        if ($query1) {
 echo '<script>alert("Your Order Successfully Booked ")</script>';
//echo "<script>window.location.href='index.php'</script>";
  }
  else
    {
      echo "<script>alert('Something went wrong.');</script>";  
    }


?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>



<form action="index.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_SESSION['amount']* 100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="CLICK ME TO DONATION"
	data-name="Payment"
    data-prefill.name="<?php echo $_POST['name'];?>"
    data-prefill.email="<?php echo $_POST['email'];?>"
    data-prefill.contact="<?php echo $_POST['contactno'];?>"
    data-theme.color="#800000"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style type="text/css">
    .razorpay-payment-button{
        display: none;
    }
</style>

<script type="text/javascript">
    $(document).ready(function(){
        $('.razorpay-payment-button').click();
    });
</script>